# _config.yml
theme: jekyll-theme-primer
with:
  source: cookbook_project/docs
title: "Tania's Cookbook"
description: "A searchable digital recipe collection."
theme: null
exclude:
  - "*.pdf"
  - "*.py"
  - "*.ipynb"
  - README.md
  - .DS_Store